### ISSUE TITLE
Error with Node 0.10

### ISSUE THREAD

**Issue by tenebroso** [laktek/punch-sftp-publisher#1]
Hey, I'm trying to install this plugin but am receiving the following error:

 304 https://registry.npmjs.org/punch
npm ERR! Error: spawn ENOENT
npm ERR!     at errnoException (child_process.js:945:11)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:736:34)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Darwin 12.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "punch-sftp-publisher"
npm ERR! cwd /Users/iMac
npm ERR! node -v v0.10.0
npm ERR! npm -v 1.2.14
npm ERR! syscall spawn
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/iMac/npm-debug.log
npm ERR! not ok code 0

**Comment by laktek** [comment]
Please try the new version of this plugin (version 1.0.2). I have changed the underlying SFTP library.
